#!/usr/bin/env bash

set -euo pipefail

EXCLUSIONS_PATH=~/.kinstall/backup.exclude

ls -A1 | sort | \
while read -r dirname; do
	if [[ ! -d "$dirname" ]]; then
		continue
	fi

	dirpath="$(cd "$dirname" && pwd)/"
	excluded="false"
	while read -r exclusion; do

		if [[ ! "$exclusion" =~ " *#.*" ]] && [[ "$exclusion" != "" ]]; then
		   	full_exclusion=^"$exclusion"
		    if [[ "$dirpath" =~ $full_exclusion ]]; then
				excluded="true"
			fi
		fi 
	done < "$EXCLUSIONS_PATH"
	if [[ "$excluded" == "false" ]]; then
		echo "$dirpath"
	fi
done

