#!/usr/bin/env bash

flag="${1:-}"

set -euo pipefail

if [[ "$flag" != -f ]]; then
	git diff --exit-code
fi

git checkout master
git fetch
git reset --hard origin/master
git-cleanbranches 2>/dev/null || echo "${0}: No branches to clean" >&2

echo "Done!" >&2
