#!/bin/sh
if xinput --set-prop 10 "Synaptics Scrolling Distance" -114, -114 || \
   xinput --set-prop 11 "Synaptics Scrolling Distance" -114, -114 || \
   xinput --set-prop 12 "Synaptics Scrolling Distance" -114, -114; then
	echo "> invertscroll success"
else
	echo "> invertscroll failed"
fi
