#!/usr/bin/env bash

set -e
set -o pipefail
set -u

if [ -z ${1+x} ]; then
	echo -n "Enter date in a format that your \`date\` command understands: "
	read -r requested_date
else
	requested_date="$*"
fi

echo "$0: Requsted date is $requested_date"

formatted_date="$(date -d "$requested_date" +%Y-%m-%d_%a | tr '[:upper:]' '[:lower:]')"
if [[ -n "$formatted_date" ]]; then
	fname="${formatted_date}.md"
else
	echo "$0: fatal: Bad day specifier."
	exit 1
fi

cd ~/kjournal
echo "$0: Editing $fname" \
&& subl --new-window --wait "$fname" \
&& echo "$0: Adding changes to be committed" \
&& git add "$fname" \
&& echo "$0: Committing changes" \
&& git commit -m "Edit $fname" \
&& echo "$0: Pushing changes" \
&& git push \
&& echo "$0: Done!"
