#!/usr/bin/env bash

set -e
set -o pipefail
set -u

ksetup_env=$(cd "$HOME"/ksetup && make settings.ENV --silent)
list_image_cmd="echo /home/kyle/pics/lock-screens/lock_${ksetup_env}.jpg"

XSECURELOCK_IMAGE_DURATION_SECONDS=3600 \
XSECURELOCK_SAVER=saver_mpv \
XSECURELOCK_LIST_VIDEOS_COMMAND="$list_image_cmd" \
xsecurelock
