#!/usr/bin/env bash

set -e
set -o pipefail
set -u
set -x 

list_image_cmd="echo ${HOME}/pics/lock-screens/lock_${KI_ENV}.jpg"

#XSECURELOCK_IMAGE_DURATION_SECONDS=3600 \
#XSECURELOCK_SAVER=saver_mpv \
#XSECURELOCK_LIST_VIDEOS_COMMAND="$list_image_cmd" \
#XSECURELOCK_WAIT_TIME_MS=100 \
xsecurelock "$@"
