#! /usr/bin/env bash

case "$1" in
  "user"|"")
    endpoint="edx-vpn.mit.edu"
    servercert="sha256:26a3f283b6e94fd75d66a02ae621e48b7c0789f62297d2b1b96b93109ca545e8"
    ;;
  "admin")
    endpoint="edx-admin-vpn.mit.edu"
    servercert="sha256:f0d27cd3d7b52658b573a9de98a016d7dc13aa084872c13a608db33e7135927a"
    ;;
esac

(cat /home/kyle/.kprivate/mit.txt ; echo "push") | \
sudo openconnect "$endpoint" --servercert "$servercert" --user=kdmccor --passwd-on-stdin
