#!/bin/bash
# Kyle McCormick
# 2015-10-20
# Ask all programs started by this window manager to close nicely

exename=`basename "$0"`
log() { echo "$exename: $@" 1>&2; }

# For each window from most to least recently created...
wmctrl -l | tac | while read win_info; do

	# Ask window politely to quit
	win_xid=$(echo $win_info | cut -d " " -f 1)
	win_title=$(echo $win_info | cut -d " " -f 4-)
	cmd="wmctrl -i -c $win_xid"
	log "trying to quit window \"$win_title\": $cmd"
	cmd="ls"

	if ! $cmd; then
		log "quit failed, skipping window"
		continue
	fi

	# Give 10 seconds for window to (ten 0.1s tries)
	quit_success=false
	for try_num in $(seq 1 100); do
		if ! [[ $(wmctrl -l | grep $win_xid) ]]; then
			log "window quitted successfully"
			quit_success=true
			break;
		fi
		sleep 0.1s
	done

	# If window failed to quit, abort.
	if ! [ "$quit_success" = true ]; then
		log "window quit timed out; aborting"
		exit 1
	fi
done

# All quitted successfully
exit 0
