#!/usr/bin/env bash

set -e
set -o pipefail
set -u
set -x

invertscroll

xset s 300 5

xss-lock --notifier=/usr/local/libexec/xsecurelock/dimmer \
         --transfer-sleep-lock -- xsecurelock

echo exiting
