#!/usr/bin/env bash

set -e
set -o pipefail
set -u
set -x

# Move this to desktop 9 (i.e. workspace 10)
win-set-desktop 9

# Enable natural scrolling.
invertscroll

# Lock screen automatically after 300 seconds. Poll every 5 milliseconds (?).
xset s 300 5

# TODO: Start apps here. Need to figure out workspaces on monitor though.

# Run screen lock handler (blocks indefinitely).
xss-lock --notifier=/usr/local/libexec/xsecurelock/dimmer \
         --transfer-sleep-lock -- xsecurelock

echo "$0: xss-lock process finished - either crashed or was interrupted."
