#!/usr/bin/env bash

set -e
set -o pipefail
set -u

if ls ~/.ssh/id_rsa.pub &>/dev/null; then
	echo "~/.ssh/id_rsa.pub present. Assuming key is created correctly. Will exit." >&2
else
	echo "~/.ssh/id_rsa.pub not present. Creating now." >&2
	cmd_base="ssh-keygen -t rsa -b 4096 -C ${KI_EMAIL} -f $HOME/.ssh/id_rsa"
	echo "+${cmd_base} -N <PASSPHRASE REDACTED>"
	$cmd_base -N "$KI_SSH_PASSPHRASE"
fi
