#!/usr/bin/env bash

flag="${1:-}"

set -euo pipefail

# Abort if uncommited changes
if [[ "$flag" != -f ]]; then
	git reset  # Unstage everything so that diff check will work.
	git diff --exit-code
fi

git switch master || git switch main
git fetch --all
git reset --hard upstream/master || git reset --hard origin/master || git reset --hard upstream/main || git reset --hard origin/main
git-cleanbranches origin
git-cleanbranches upstream || true

echo "Done!" >&2
